name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22.x]
        os: [ubuntu-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version
      - run: go test -shuffle=on ./...
      - run: go test -race -shuffle=on ./...
